# .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Documentation:
  Enabled: false

IndentationConsistency:
  EnforcedStyle: 'rails'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/LineLength:
  Max: 95

Layout/AlignParameters:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
